# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Rails.application.secrets.some_api_key returns SOMEKEY in the development environment.

development: &default
  secret_key_base: d3d8af6b7777d1977f98852fab9e87944af446f2f89ea31a5f69642ca4cc9803818d9602742ce8606ffb473894897cf9bde416024cdd0d07bc5366086931379f

  # For basic authentication
  username: ""
  password: ""

test: *default
  #secret_key_base: 4b91450a40cd06d458dc1ca4020e155d69fd732b9cea56130d5ad5c4ae9eb07ce136a8d6210e28aec48196eaed33d6948e6bd200b333660cfca3602ec4764a58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  # For basic authentication
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
